export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const STAGING = 'staging';
// export const SURVEY_REPOSITORY = 'SURVEY_REPOSITORY';
// export const SURVEY_QUESTION_REPOSITORY = 'SURVEY_QUESTION_REPOSITORY';
// export const SURVEY_GROUP_REPOSITORY = 'SURVEY_GROUP_REPOSITORY';
// export const SURVEY_DETAILED_TARGET_REPOSITORY =
//   'SURVEY_DETAILED_TARGET_REPOSITORY';
// export const QUESTION_OPTION_REPOSITORY = 'QUESTION_OPTION_REPOSITORY';
// export const QUESTION_LIKERT_REPOSITORY = 'QUESTION_LIKERT_REPOSITORY';
// export const QUESTION_TEXT_REPOSITORY = ' QUESTION_TEXT_REPOSITORY';
// export const TARGET_AUDIENCE_REPOSITORY = 'TARGET_AUDIENCE_REPOSITORY';
// export const USER_SURVEY_REPOSITORY = 'USER_SURVEY_REPOSITORY';
// export const RESPONSE_REPOSITORY = ' RESPONSE_REPOSITORY';
// export const REWARD_REPOSITORY = ' REWARD_REPOSITORY';
// export const USER_AUTHORIZE_REPOSITORY = ' USER_AUTHORIZE_REPOSITORY';
// export const SURVEY_RECEIVER_REPOSITORY = ' SURVEY_RECEIVER_REPOSITORY';
// export const SURVEY_ACCOUNT_REPOSITORY = ' SURVEY_ACCOUNT_REPOSITORY';
// export const REWARD_AUTH_REPOSITORY = ' REWARD_AUTH_REPOSITORY';
// export const MARGIN_ERROR_RESPONSE_SIZE = 'MARGIN_ERROR_RESPONSE_SIZE';
// export const SURVEY_TARGET_RESPONSE_REPOSITORY =
//   'SURVEY_TARGET_RESPONSE_REPOSITORY';

export const SEQUELIZE_INSTANCE = 'SequelizeInstance';
